//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by psynteg.rc
//
#define IDS_STREAM_FNAME2               2
#define IDS_INSTR_NIC2                  5
#define IDS_NIC2_DLL1                   10
#define IDS_NIC2_DLL2                   11
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CONSTANT                    101
#define IDD_psynteg_DIALOG              102
#define IDS_STRING102                   102
#define IDS_STRING103                   103
#define IDS_STRING_HELP1                104
#define IDS_STRING_HELP2                105
#define IDS_STRING_HELP3                106
#define IDS_STRING_HELP4                107
#define IDS_STRING_HELP5                108
#define IDS_STRING_HELP6                109
#define IDS_STRING_HELP7                110
#define IDS_STRING_HELP8                111
#define IDR_MAINFRAME                   128
#define IDR_PSY                         128
#define IDD_ADAPTIVE                    129
#define IDD_SLIDER                      130
#define IDD_PLOT                        131
#define IDD_SETTINGS                    132
#define IDD_SMALL                       134
#define IDR_MENU1                       134
#define IDD_SET_PROCESSOR               135
#define IDD_prank                       136
#define IDI_ICON1                       137
#define IDI_ICON2                       138
#define IDD_CUSTOM						139
#define IDC_BRICS2                      1002
#define IDC_BRICS                       1003
#define IDC_PLAY                        1004
#define IDC_OPEN1                       1005
#define IDC_OPEN                        1005
#define IDC_PERTRIAL                    1005
#define IDC_PLAY2                       1006
#define IDC_INIT_VAL                    1007
#define IDC_TAGS                        1007
#define IDC_STEP1                       1008
#define IDC_TRIALS                      1008
#define IDC_RANGE1                      1008
#define IDC_NUM_INTERVALS               1008
#define IDC_REVERSALS1                  1009
#define IDC_RANGE2                      1009
#define IDC_SAVE1                       1009
#define IDC_SAVE                        1009
#define IDC_SPRINT                      1009
#define IDC_TAGS2                       1009
#define IDC_STEP2                       1010
#define IDC_L34                         1010
#define IDC_REVERSALS2                  1011
#define IDC_PROCESSOR_GRP               1011
#define IDC_STATIC_DIRECTION            1012
#define IDC_CIC3                        1012
#define IDC_EDIT_GET                    1013
#define IDC_IND_VAR_STR                 1013
#define IDC_CIC4                        1013
#define IDC_FINAL_REV_4AVG              1014
#define IDC_IMPLANT_GRP                 1014
#define IDC_SP12                        1015
#define IDC_EMUL                        1016
#define IDC_GO                          1017
#define IDC_STOP                        1018
#define IDC_MANUAL_MORE_RANGE           1018
#define IDC_RADIO1                      1019
#define IDC_RADIO2                      1020
#define IDC_DOWN                        1020
#define IDC_RADIO3                      1021
#define IDC_UP                          1021
#define IDC_FEEDBACK                    1022
#define IDC_COMP_EDIT                   1023
#define IDC_DELAY_INTERVALS             1024
#define IDC_DELAY_TRIALS                1025
#define IDC_LOG                         1026
#define IDC_ROVING                      1026
#define IDC_COMP_GRP                    1026
#define IDC_EMAIL_ADDRESS               1026
#define IDC_BEGIN_VAL                   1027
#define IDC_COMP_STAT1                  1027
#define IDC_FTP_ADDRESS                 1027
#define IDC_END_VAL                     1028
#define IDC_COMP_STAT2                  1028
#define IDC_FTP_ID                      1028
#define IDC_STEP                        1029
#define IDC_DELAY_INTERVALS5            1029
#define IDC_FTP_PASSWORD                1029
#define IDC_HOWMANY                     1030
#define IDC_COMMON_SET                  1031
#define IDC_VAR_INDEX                   1032
#define IDC_PROC_VAR                    1032
#define IDC_LOOKUP                      1033
#define IDC_STIM_VAR                    1033
#define IDC_INST                        1034
#define IDC_FROZEN_ROVING               1035
#define IDC_INST2                       1035
#define IDC_UDFPATH                     1035
#define IDC_SUBJ_ID                     1036
#define IDC_EDIT1                       1037
#define IDC_TEXT                        1037
#define IDC_MOD_SETTINGS                1038
#define IDC_MOD_SETTINGS2               1039
#define IDC_PWFRAME                     1040
#define IDC_COND_E                      1041
#define IDC_COND_CL                     1042
#define IDC_COND_RATE                   1043
#define IDC_COND_ONOFF                  1044
#define IDC_ASCENDING                   1045
#define IDC_SUBJ_ID2                    1045
#define IDC_LIMIT_CHARGE                1045
#define IDC_PW                          1045
#define IDC_DESCENDING                  1046
#define IDC_PG                          1046
#define IDC_DEFAULT_PWPG                1046
#define IDC_ANCHOR_STANDARD             1049
#define IDC_STATIC_VER                  1050
#define IDC_FOR1                        1051
#define IDC_FOR2                        1052
#define IDC_TASKTAB                     1052
#define IDC_AUTO                        1053
#define IDC_IND_VAR_COUNT_STATIC        1054
#define IDC_CHECK1                      1056
#define IDC_FACTOR                      1056
#define IDC_CUR_VAL                     1057
#define IDC_LOG_EMAIL                   1058
#define IDC_LOG_FTP                     1059
#define IDC_CUSTOM_SCRIPT               1060
#define ID_FILE_SETTINGS                32771
#define ID_FILE_EXIT                    32772
#define ID_FILE_OPENSTIM                32773
#define ID_FILE_SAVESTIM                32774
#define ID_FILE_HARDWARECONFIG          32775
#define ID_FILE_RESETPROCESSOR          32776
#define ID_ADVFEATURES_AUTO             32777
#define ID_ADVFEATURES                  32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
