//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Echo.rc
//
#define IDS_TOKEN1                      1
#define IDS_TOKEN2                      2
#define IDS_TOKEN3                      3
#define IDS_TOKEN4                      4
#define IDS_TOKEN5                      5
#define IDS_TOKEN6                      6
#define IDS_TOKEN7                      7
#define IDS_TOKEN8                      8
#define IDS_TOKEN9                      9
#define IDS_TOKEN10                     10
#define IDS_TOKEN11                     11
#define IDS_TOKEN12                     12
#define IDS_TOKEN13                     13
#define IDS_TOKEN14                     14
#define IDS_TOKEN15                     15
#define IDS_TOKEN16                     16
#define IDS_TOKEN17                     17
#define IDS_TOKEN18                     18
#define IDS_TOKEN19                     19
#define IDS_TOKEN20                     20
#define IDS_TOKEN21                     21
#define IDS_TOKEN22                     22
#define IDS_APPLICATION_ID              50
#define IDS_SUBJ_INST1                  51
#define IDS_SUBJ_INST2                  52
#define IDS_SUBJ_INST3                  53
#define IDS_SUBJ_INST4                  54
#define IDS_SUBJ_INST5                  55
#define IDS_SUBJ_INST6                  56
#define IDS_HELPSTRING                  57
#define IDD_MULTIPLEX                   101
#define IDI_ICON1                       109
#define IDR_MENU1                       112
#define IDR_ACCELERATOR1                114
#define IDD_PRESENTER_FAIL              116
#define IDR_241                         118
#define IDD_SETTINGS                    133
#define IDC_OPEN_SESSION                1001
#define IDC_UPDATE                      1002
#define IDC_SAVE_SESSION                1003
#define IDC_SESSION_NAME                1004
#define IDC_WAV_DIRECTORY               1005
#define IDC_WAVELIST                    1006
#define IDC_WAVELIST2                   1007
#define IDC_PLAYLIST                    1008
#define IDC_RESPONSELOG                 1009
#define IDC_NAMERULE                    1010
#define IDC_NUM_COMBO                   1011
#define IDC_FS                          1033
#define IDC_UDFPATH                     1035
#define IDC_NUM_TRIALS                  1036
#define IDC_BEGIN                       1037
#define IDC_STOP                        1040
#define IDC_PRESENTER                   1043
#define IDC_NOTE2SAVE                   1052
#define IDC_WAVREADY                    1054
#define IDC_EMAIL_ADDRESS               1054
#define IDC_FTP_ADDRESS                 1055
#define IDC_NUM_FOLDER_FILES            1056
#define IDC_FTP_ID                      1056
#define IDC_CONNECT_PRESENTER           1057
#define IDC_FTP_PASSWORD                1057
#define IDC_LOG_EMAIL                   1058
#define IDC_LOG_FTP                     1059
#define IDC_NODELIST                    1060
#define IDC_LEVEL                       1062
#define IDC_SUMMARY                     1062
#define IDC_MISSINGFILES                1063
#define IDC_SAVE2FILE                   1065
#define IDC_FEEDBACK                    1066
#define IDC_ACOUSTIC                    1067
#define IDC_TALK                        1068
#define IDC_PRACTICE                    1069
#define IDC_FEEDBACK2                   1070
#define IDC_1RESPONSE                   1070
#define IDC_ALLOWSAME                   1071
#define IDC_ALLOWSAMEWAV                1071
#define IDC_ALLOWSAMETOKEN              1071
#define IDC_ADDPROC                     1076
#define IDC_PRESENT_CONTROL             1077
#define IDC_PROC                        1078
#define IDC_NUM_STIM                    1079
#define IDC_GAP                         1080
#define IDC_GAP_CAPTION                 1082
#define IDC_MSG_LOG                     1084
#define IDC_CONS                        1085
#define IDC_GENERAL                     1086
#define IDC_GENERAL_LIST                1087
#define IDC_GENERAL_INST1               1088
#define IDC_GENERAL_INST2               1089
#define IDC_SESSION_FNAME               1090
#define IDC_PREV_BATCH                  1091
#define IDC_CURRENT_BATCH               1092
#define IDC_GO                          1093
#define IDC_SINGLE                      1094
#define IDC_DUAL                        1095
#define IDC_PRESENTER_SET               1097
#define IDC_TOTALTRIALS                 1102
#define IDC_MSG                         1103
#define IDC_RETRY                       1106
#define IDC_STEREO                      1108
#define IDC_CURRENT_SCORE               1109
#define IDC_CURRENT_CORR                1112
#define IDC_CURRENT_TRIALS              1113
#define ID_MENUITEM40005                40005
#define IDM_BATCH                       40006
#define ID_HELP_ECHO                    40007
#define ID_HELP_ABOUT                   40008
#define IDM_MULTIPLEX                   40010
#define IDM_FILE_SETTINGS               40014
#define IDM_FILE_SAVESESSION            40020
#define IDM_FILE_OPENSESSION            40021
#define IDM_FILE_EXIT                   40023

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40024
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
