//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by psycon.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CONSTANT                    101
#define IDD_PSYCON_DIALOG               102
#define IDS_STRING103                   103
#define IDD_REMOTE_HOSTS                104
#define IDS_STRING104                   104
#define IDS_STRING105                   105
#define IDS_STRING106                   106
#define IDD_ADAPTIVE                    129
#define IDR_MENU1                       129
#define IDD_SLIDER                      130
#define IDD_LICENSE                     131
#define IDD_SETTINGS                    133
#define IDI_PSYCON                      133
#define IDD_CONSTANT_LOG                135
#define IDD_CONSTANT1                   136
#define IDD_CUSTOM                      136
#define IDC_CANCEL                      1001
#define IDC_SIGNAL_CON                  1002
#define IDC_HOST_LIST                   1002
#define IDC_SIGNAL_REF                  1003
#define IDC_REMOVE_HOST                 1003
#define IDC_ADD_HOST                    1004
#define IDC_NEWHOST                     1005
#define IDC_SIGNAL_TAG                  1006
#define IDC_INIT_VAL                    1007
#define IDC_NUM_INTERVALS               1007
#define IDC_TRIALS                      1008
#define IDC_STEP1                       1008
#define IDC_VAL                         1008
#define IDC_SIGNAL_TAG2                 1008
#define IDC_REVERSALS1                  1009
#define IDC_STEP2                       1010
#define IDC_REVERSALS2                  1011
#define IDC_ANCHOR_INT                  1012
#define IDC_SINGLEPLAY                  1013
#define IDC_TRIAL_LIMIT                 1013
#define IDC_IND_VAR_STR                 1013
#define IDC_FINAL_REV_4AVG              1014
#define IDC_PROCEDURE_PLAY              1014
#define IDC_SAVEDETAIL                  1015
#define IDC_CROSSING_LIMIT              1015
#define IDC_TALK                        1016
#define IDC_USE_AS_CONTROLLER           1016
#define IDC_GO                          1017
#define IDC_STOP                        1018
#define IDC_DOWN                        1020
#define IDC_UP                          1021
#define IDC_FEEDBACK                    1022
#define IDC_DELAY_INTERVALS             1024
#define IDC_SUBJ                        1024
#define IDC_DELAY_TRIALS                1025
#define IDC_LOG                         1026
#define IDC_VOL2                        1026
#define IDC_BEGIN_VAL                   1027
#define IDC_VOL_CAL1                    1027
#define IDC_VOL_CAL2                    1028
#define IDC_STEP                        1029
#define IDC_ASCENDING                   1029
#define IDC_CAL_LEVEL1                  1029
#define IDC_HOWMANY                     1030
#define IDC_DESCENDING                  1030
#define IDC_STEP_BIG                    1030
#define IDC_CAL_LEVEL2                  1030
#define IDC_STEP_SMALL                  1031
#define IDC_CALTONE_FREQ                1031
#define IDC_PLAY_STOP                   1032
#define IDC_MAX_LEVEL                   1033
#define IDC_FS                          1033
#define IDC_INST                        1034
#define IDC_UDFPATH                     1035
#define IDC_CONTROLLER_NODE             1036
#define IDC_VOL1                        1037
#define IDC_CODE                        1037
#define IDC_RESULT_LOG                  1037
#define IDC_CONTROLLER_LEVEL            1038
#define IDC_UPDATE_CAL                  1039
#define IDC_COPY_VOL1                   1040
#define IDC_COPY_VOL2                   1041
#define IDC_SLIDER1                     1042
#define IDC_MAXVOL_CAPTION1             1043
#define IDC_SLIDER2                     1044
#define IDC_MAXVOL_CAPTION2             1045
#define IDC_TASKTAB                     1045
#define IDC_CHECK                       1051
#define IDC_IND_VAR_COUNT_STATIC        1054
#define IDC_EMAIL_ADDRESS               1054
#define IDC_WARNING_STATIC              1055
#define IDC_FTP_ADDRESS                 1055
#define IDC_FACTOR                      1056
#define IDC_FTP_ID                      1056
#define IDC_FTP_PASSWORD                1057
#define IDC_LOG_EMAIL                   1058
#define IDC_STATIC8                     1058
#define IDC_LOG_FTP                     1059
#define IDC_STATIC9                     1059
#define IDC_STATIC_PSYCON               1060
#define IDC_CUSTOM_SCRIPT               1061
#define IDC_BUTTON1                     1062
#define IDC_EXT_EDITOR                  1062
#define IDM_FILE_SETTINGS               32774
#define IDM_FILE_OPENSTIM               32775
#define IDM_FILE_SAVESTIM               32776
#define IDM_FILE_EXIT                   32777
#define IDM_HELP_WHATSNEW               32781
#define IDM_HELP_ABOUT                  32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
